services: # Define services
  mysql: # Define MySQL service
    build: . # Build MySQL image from Dockerfile in the same directory
    container_name: mysql_service # Name the container
    environment: # Set environment variables
      MYSQL_ROOT_PASSWORD: root # Set MySQL root password
      MYSQL_DATABASE: my_database # Create a database named my_database
      MYSQL_USER: user # Create a user named user
      MYSQL_PASSWORD: password # Set user password
    ports: # Expose MySQL port
      - "3310:3306" # Map container port 3306 to host port 3306
    volumes: # Attach volumes
      - ./mysql_data:/var/lib/mysql  # Attach volume to persist MySQL data in the same directory